// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHlThu2eWuwyTgIyBso2utwCT0TLbpWPo',
    appId: '1:1061712842866:web:632ed5e0318da8778a32eb',
    messagingSenderId: '1061712842866',
    projectId: 'garbomanage',
    authDomain: 'garbomanage.firebaseapp.com',
    storageBucket: 'garbomanage.appspot.com',
    measurementId: 'G-6QZT5682SD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBC0YckVkwjWj31OW8gIUObSu9nBZvSfuI',
    appId: '1:1061712842866:android:29db9ec02f64fe728a32eb',
    messagingSenderId: '1061712842866',
    projectId: 'garbomanage',
    storageBucket: 'garbomanage.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCt3HMr7kD1MTPT5Pa0RNrQUaLwhdXwnD4',
    appId: '1:1061712842866:ios:b8749a8adcea26ca8a32eb',
    messagingSenderId: '1061712842866',
    projectId: 'garbomanage',
    storageBucket: 'garbomanage.appspot.com',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCt3HMr7kD1MTPT5Pa0RNrQUaLwhdXwnD4',
    appId: '1:1061712842866:ios:b8749a8adcea26ca8a32eb',
    messagingSenderId: '1061712842866',
    projectId: 'garbomanage',
    storageBucket: 'garbomanage.appspot.com',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHlThu2eWuwyTgIyBso2utwCT0TLbpWPo',
    appId: '1:1061712842866:web:437d9bf3167347208a32eb',
    messagingSenderId: '1061712842866',
    projectId: 'garbomanage',
    authDomain: 'garbomanage.firebaseapp.com',
    storageBucket: 'garbomanage.appspot.com',
    measurementId: 'G-1CCPWKV7Q9',
  );
}
